# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Shadowplay
email: DMsShadow@hotmail.com

description: > # this means to ignore newlines until "baseurl:"
  The ramblings of a TTRPG Games Master and PD for the SKW in Phoenix BSE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmsshadow.com" # the base hostname & protocol for your site

twitter_username: dmsshadow
github_username:  dmsshadow


# Build settings
markdown: kramdown
